### ISSUE TITLE
Using NeoUart on Orange Pi

### ISSUE THREAD

**Issue by snowsquizy** [bigjosh/NeoUart#3]
I am trying to currently get this to work with an Orange PI using uart3.  Does this work on a specific uart and if so can this be easily changed to allow compatiability.
T.I.A

**Comment by bigjosh** [comment]
NeoUart is unlikely to work on the Orange PI without modification. It talks directly to the registers on the Broadcom chip on the Raspberry Pi. The Orange has a different chip, so while it is probably possible to get this strategy to work, you'd need to dig into the Allwinner datasheet to figure out how.
