### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by gazhay** [bigjosh/NeoUart#4]
Wired up as shown - got nothing - no errors - no pixel light.
Swapped to GPIO18 and tried https://github.com/jgarff/rpi_ws281x.git
and that seemed to work fine - so I know my pixel is wired correctly.

Trying on an rpi3 with latest raspbian pixel.

**Comment by bigjosh** [comment]
The Raspberry PI 3 [totally messed with the serial ports](http://raspberrypi.stackexchange.com/a/45571/31486). While it is probably *possible* to get this technique to work on a 3, you'd have to figure out the new pins and new register addresses and do lots of hardware config on the PI.

**Comment by gazhay** [comment]
Ah ok, no problems
