### ISSUE TITLE
Using a USB UART

### ISSUE THREAD

**Issue by steveschnepp** [bigjosh/NeoUart#6]
Thanks for your awesome post that [inspired me](https://blog.pwkf.org/2024/03/20/drive-ws2812-uart.html).

I managed to leverage a simple USB/TTL uart to drive the neopixels.

And I also extended the NUA protocol to cope with strips as, actually, it works quite well.

**Comment by bigjosh** [comment]
Sweet! I added a link at the bottom of the post here...
https://wp.josh.com/2014/09/03/inside-neouart-tricking-a-serial-port-into-being-a-signal-generator/
